server:
  port: 80

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    preferIpAddress: true
    nonSecurePort: 80

spring:
  application:
    name: user-service
  data:
    mongodb:
      database: user
      port: 27018
      host: user-mongo

#  spring.data.mongodb.host=user-mongo
#  spring.data.mongodb.port=27018
#  spring.data.mongodb.database=user
#  server.port=8081
#
#  management.endpoints.web.exposure.include=*
#  management.endpoint.health.show-details=always
#
#  spring.application.name=user-service
#  eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka