global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'raspador do prometheus'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['product-app-instance:8080', 'user-app-instance:8081', 'order-app-instance:8082']