management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    preferIpAddress: true
    nonSecurePort: 8082

spring:
  application:
    name: order-service
  data:
    mongodb:
      database: order
      port: 27019
      host: order-mongo

server:
  port: 8082

#  server.port=8082
#  spring.data.mongodb.host=order-mongo
#  spring.data.mongodb.port=27019
#  spring.data.mongodb.database=orders
#
#  management.endpoints.web.exposure.include=*
#  management.endpoint.health.show-details=always
#
#  product.base.url=http://product-app-instance:8080/product/%s
#  user.base.url=http://user-app-instance:8081/user/%s
#
#  spring.application.name=order-service
#  eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka