server:
  port: 80

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    preferIpAddress: true
    nonSecurePort: 80

spring:
  application:
    name: product-service
  data:
    mongodb:
      database: product
      port: 27017
      host: product-mongo

#      spring.data.mongodb.host=product-mongo
#      spring.data.mongodb.port=27017
#      spring.data.mongodb.database=product
#      server.port=8080
#
#      management.endpoints.web.exposure.include=*
#      management.endpoint.health.show-details=always
#
#      spring.application.name=product-service
#      eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka